# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: codogo/pipelines-jekyll-aws:1.2.0

pipelines:
  default:
    - step:
        script:
          - tree
          - npm install
          - bash -ex Scripts/build-dev.sh
          - bash -ex Scripts/deploy-dev.sh
          - echo "codogo-nhs-site-ihub-dev.s3-website-eu-west-1.amazonaws.com/$BITBUCKET_BRANCH/"

  branches:
    master:
      - step:
          script:
            - tree
            - npm install
            - bash -ex Scripts/build-master.sh
            - bash -ex Scripts/deploy-master.sh
            - echo "codogo-nhs-site-ihub-prod.s3-website-eu-west-1.amazonaws.com/"

